### ISSUE TITLE
Determine Competency Framework

### ISSUE THREAD

**Issue by okeala** [ianksalter/Sail#1]

**Comment by okeala** [comment]
This task will be completed when:
1) All the references files are created
2) The [syllabi spreadsheet](https://docs.google.com/spreadsheets/d/1thgdA9iUCdyFXX0nb_yZbbMUU_cIoOOk9Hl_vyt1eQw/edit#gid=1866121123) shows hiearchical structure of the references section

**Comment by ianksalter** [comment]
Reference section completed as far as is sensible at commit: 814da86544976c9e6a711f125b44ddca561e394b and spreadsheet updated.
